### ISSUE TITLE
Add info tooltip for the duration input

### ISSUE THREAD

**Issue by PaulRBerg** [TomAFrench/sablier-safe-app#37]
This is arguably the hardest stream property to convey the meaning of to end users. A nice little tooltip that explains what the duration is about would be a boon.

The black box on the left-hand side of this image is what I'm referring to:

<img alt="Tooltip Image" src="https://i.pinimg.com/474x/c0/ef/66/c0ef66223ba519626e944e810a95f654--ios-ui-interface-design.jpg"/>

**Comment by TomAFrench** [comment]
I think that the new update makes this sufficiently clear.
