### ISSUE TITLE
Tap row item and open the Sablier Interface page

### ISSUE THREAD

**Issue by PaulRBerg** [TomAFrench/sablier-safe-app#43]
It'd be nice to redirect the user to the Sablier Interface when they tap a row in the "Manage Created Streams" table.

There's no way we will ever fit as much rich data in the Safe App as there can be displayed on the canonical web app.

**Comment by TomAFrench** [comment]
If the vertical space in the Gnosis ui allows I'd like to pull in "expand transaction" behaviour from the transaction page to display a fair amount of this information (likely not all so would also include a link to the canonical web app).

Adding a quick link to the existing table would be a good stop-gap

**Comment by PaulRBerg** [comment]
Just for the record, can you share a screenshot that shows how the "<expand transaction> behaviour from the transaction page" works?

**Comment by TomAFrench** [comment]
Sure I've got an image up in the PR of how it currently looks for us but on the Gnosis' transactions page it looks like the below screenshot.

![Screenshot_2020-06-11_17-42-52](https://user-images.githubusercontent.com/15848336/84415675-0531f800-ac0b-11ea-98b7-8e3a9de9febd.png)


On the left, general information is displayed on the transaction while actions which are available to the user are placed in the pane on the right.

**Comment by PaulRBerg** [comment]
Oh, I see. And is your intent to duplicate this data in the Sablier app or only mimic the UI but use the stream-specific data? If the former, I don't think it's worth it. If the latter, that'd be nice, but not too much data.

**Comment by TomAFrench** [comment]
Yeah I'm wanting to have pretty much just stream specific information. I've outlined my thoughts in the PR.

**Comment by PaulRBerg** [comment]
Closing this in favour of the expandable row system implemented in #54.
