### ISSUE TITLE
Build token list for mainnet

### ISSUE THREAD

**Issue by TomAFrench** [TomAFrench/sablier-safe-app#45]
The app needs a list of tokens which can be used on mainnet. This is limited to those indexed by the [sablier subgraph](https://github.com/sablierhq/sablier-subgraph)

**Comment by PaulRBerg** [comment]
> This is limited to those indexed by the sablier subgraph

This is true, but it's not like I can't modify that if we have to. If there's demand for a specific ERC20, we'll add it.

**Comment by TomAFrench** [comment]
Yep, 100% true. I was just being explicit on requirements.
