### ISSUE TITLE
Add proper empty state handling for stream table.

### ISSUE THREAD

**Issue by TomAFrench** [TomAFrench/sablier-safe-app#47]
Currently we have a situation where when navigating to the stream table page while no streams exist it results in a permanent loading spinner. We could add an empty state to the table to avoid user confusion.

I'm of a mind to instead move the querying of the subgraph into the `App` component and pass the streams in as a prop in order to hide the loading time. We could solve this issue at the same time by disabling the `Manage Created Streams` button if this list is empty.

**Comment by PaulRBerg** [comment]
100% agree. Brilliant idea.

There might be some cases when the streams load so slowly that the user won't ever be able to see the "Manage Created Streams" button, yet those should be rare.
