### ISSUE TITLE
Uncaught (in promise) Error: missing response (serverError={}

### ISSUE THREAD

**Issue by PaulRBerg** [TomAFrench/sablier-safe-app#57]
Not sure what's the cause of this, or if it does any harm at all:

```
index.js:165 Uncaught (in promise) Error: missing response (serverError={}, url="https://mainnet.infura.io/v3/84842078b09946638c03157f83405213", code=SERVER_ERROR, version=web/5.0.0-beta.141)
    at Logger.makeError (index.js:165)
    at Logger.throwError (index.js:174)
    at index.js:100
    at Generator.throw (<anonymous>)
    at rejected (index.js:6)
```

**Comment by TomAFrench** [comment]
Yeah, this line seems to be having issues connecting to Infura which is resulting in it reporting a zero token balance for the safe.

https://github.com/TomAFrench/sablier-safe-app/blob/6b28e53481c1055d6c4ed12378be4d13d16cf867/src/components/CreateStreamForm/index.tsx#L169

I've swapped it out for the `getDefaultProvider` function and I end up with the fallback provider.
